apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: naptime
spec:
  params:
    - name: duration
      default: '2h'
  tasks:
  - name: sleep
    timeout: "2h0m0s"
    params:
      - name: duration
        value: $(params.duration)
    taskSpec:
      params:
        - name: duration
          type: string
      steps:
        - name: sleep
          image: registry.access.redhat.com/ubi9/ubi-micro
          script: |
            echo "**********************"
            echo "Sleeping for $(params.duration)"
            sleep "$(params.duration)"
            echo "**********************"
